spring:
  application:
    name: client001
server:
  port: 8888
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7777/eureka
  instance: # eureak实例定义
    hostname: hdd.com # 定义Eureka实例所在的主机名称
    instance-id: dept-8001.com  # 在信息列表时显示主机名称